# Generated by Django 5.0.6 on 2024-05-11 21:34
from django.db import migrations


def populate_roles(apps, schemaeditor):
    # define roles dictionary
    roles = {
        "Developer": "The person on the team who works on issues",
        "Product Owner": "The person on the team who writes issues",
        "Scrum Master": "The team's coach",
    }

    # retrieve Role model from accounts app
    Role = apps.get_model("accounts", "Role")
    
    # create Role object for each key-value pair in roles dictionary 
    for key, value in roles.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

def populate_teams(apps, schemaeditor):
    # define teams dictionary
    teams = {
        "Alpha": "The A team",
        "Bravo": "The B team",
        "Charlie": "The C team",
    }

    # retrieve Team model from accounts app
    Team = apps.get_model("accounts", "Team")

    # create Team object for each key-value pair in teams dictionary 
    for key, value in teams.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
        migrations.RunPython(populate_teams),
    ]